### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by evanwill** [hanruizhang/zhanglab#1]
@hanruizhang you have left my Google Analytics ID in your [_config.yml](https://github.com/hanruizhang/zhanglab/blob/master/_config.yml) so I get stats for your site. 
The variable looks like:

`google_analytics: UA-74844011-1`

If you could please comment that out `#` or delete the value, my template will automatically not add Analytics. Or you could start your own [Analytics account](https://analytics.google.com/analytics/web/) if you would like to collect statistics, simply replace my ID with your own. 

Thanks!

**Comment by hanruizhang** [comment]
Thank you! And your github page tutorial was super helpful!
